services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: my-app-backend
    command: flask run --host=0.0.0.0 --port=5000
    restart: always
    volumes:
      - ./backend:/app
      - ./backend/credentials.json:/app/credentials.json
      - ./backend/token.json:/app/token.json
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DRIVE_FOLDER_ID=${DRIVE_FOLDER_ID}
      - GOOGLE_CREDENTIALS_PATH=${GOOGLE_CREDENTIALS_PATH}
      - GOOGLE_TOKEN_PATH=${GOOGLE_TOKEN_PATH}

      # Flaskをデバッグモードにする（これでホットリロードが有効になります）
      # 開発時は 1 (有効)、本番時は 0 にする
      - FLASK_ENV=development
      - FLASK_DEBUG=1

    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: my-app-frontend
    restart: always
    # ローカルの ./frontend と コンテナの /app を同期
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - "8501:8501"
    # 検証用に追加 start 
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    # 検証用に追加 end
    networks:
      - app-network


  #
  # 開発デバッグ用
  # 
  mailpit:
      image: axllent/mailpit
      container_name: mailpit
      restart: always
      ports:
        - "1025:1025" # SMTPサーバー（プログラムからの送信先）
        - "8025:8025" # Web管理画面（ブラウザでメールを確認する用）
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: